### ISSUE TITLE
What are the difference of SpatialConvolution, SpatialConvolutionMM, and SpatialConvolutionVirtualMM?

### ISSUE THREAD

**Issue by austingg** [mvitez/thnets#11]
There are three types function to compute convolution? what are the diferences?

**Comment by mvitez** [comment]
SpatialConvolution computes the convolution directly, as by definition of convolution.
SpatialConvolutionMM uses the im2col algorithm by creating a Toeplitz matrix and using a matrix-by-matrix multiplication, for which we have a very fast implementation in OpenBLAS. This is the way Torch calculates convolutions. The advantage is a greater speed, but the Toeplitz matrix can become very big, so this algorithm takes a lot of memory to run.
SpatialConvolutionVirtualMM does the same as before, but instead of calculating the Toeplitz matrix at the beginning, it calculates it on the fly as required by the matrix-by-matrix multiplication routine. It is faster than the previous, but mostly it does not take all the memory of the previous algorithm.

**Comment by austingg** [comment]
so the SpatialConvolutionVirtMM is the best?

**Comment by mvitez** [comment]
Yes. It's default because it's the best.

**Comment by austingg** [comment]
however when I run the thnets on android, seem all the module type are spatialConvolution ,even though I used `THUseSpatialConvolutionMM with alg = 2.

**Comment by mvitez** [comment]
If you compile with USEBLAS defined, VirtMM will be excluded, but MM should still be enabled, so I don't know.

**Comment by austingg** [comment]
yes, I opened the USEBLAS flags.
